# Generated by Django 6.0.3 on 2026-03-13 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название сферы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя (slug)')),
            ],
            options={
                'verbose_name': 'Сфера (Категория)',
                'verbose_name_plural': 'Сферы (Категории)',
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Профессия / Тема')),
                ('description', models.TextField(blank=True, verbose_name='Описание (Легенда)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (монет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='В корзине (Soft Delete)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='Иконка/Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='api.category', verbose_name='Сфера')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (Admin)')),
            ],
            options={
                'verbose_name': 'Шаблон интервью',
                'verbose_name_plural': 'Шаблоны интервью',
            },
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('full_data_json', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='В корзине (Soft Delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='api.interviewtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История сессии',
                'verbose_name_plural': 'История сессий',
            },
        ),
    ]
