# Generated by Django 6.0.3 on 2026-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='mode',
            field=models.CharField(choices=[('roleplay', 'Сюжетное собеседование'), ('quiz', 'Проверка знаний (Викторина)')], default='roleplay', max_length=20, verbose_name='Тип режима'),
        ),
    ]
