# Generated by Django 6.0.3 on 2026-03-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interviewtemplate_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtemplate',
            name='price',
        ),
    ]
