# Generated by Django 6.0.3 on 2026-04-08 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_interviewtemplate_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия / Тема (EN)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Профессия / Тема (RU)'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_balance', models.IntegerField(default=10, verbose_name='Баланс монет ⚡️')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
