# Generated by Django 6.0.3 on 2026-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interviewtemplate_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coins_balance',
            field=models.FloatField(default=10.0, verbose_name='Баланс монет ⚡️'),
        ),
    ]
