# Generated by Django 6.0.3 on 2026-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_coins_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
