# Generated by Django 6.0.3 on 2026-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sessionhistory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_reward',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя ежедневная награда'),
        ),
    ]
