# Generated by Django 6.0.3 on 2026-05-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_last_daily_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Отображаемое название категории профессий', max_length=100, unique=True, verbose_name='Название сферы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', unique=True, verbose_name='URL-имя (slug)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='category',
            field=models.ForeignKey(help_text='К какой категории относится', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='api.category', verbose_name='Сфера'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Детальное описание для пользователя', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='description_en',
            field=models.TextField(blank=True, help_text='Английское описание', null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение карточки', null=True, upload_to='templates/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображать ли шаблон в приложении', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Метка мягкого удаления', verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='mode',
            field=models.CharField(choices=[('roleplay', 'Сюжетное собеседование'), ('quiz', 'Проверка знаний (Викторина)')], default='roleplay', help_text='Определяет логику работы ИИ (опрос или отыгрыш роли)', max_length=20, verbose_name='Тип режима'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='owner',
            field=models.ForeignKey(help_text='Администратор, создавший шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='title',
            field=models.CharField(help_text='Русское название шаблона', max_length=200, verbose_name='Профессия / Тема (RU)'),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='title_en',
            field=models.CharField(blank=True, help_text='Английское название шаблона', max_length=200, null=True, verbose_name='Профессия / Тема (EN)'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время начала сессии'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='full_data_json',
            field=models.JSONField(blank=True, default=dict, help_text='Полная история переписки и конфиг сессии в формате JSON'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Метка мягкого удаления', verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='is_failed',
            field=models.BooleanField(default=False, help_text='Флаг провала (например, за троллинг)'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Флаг успешного завершения сессии'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Итоговый балл, выставленный ИИ', max_digits=4),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='template',
            field=models.ForeignKey(help_text='Использованный шаблон (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='api.interviewtemplate'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, проходящий интервью', on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coins_balance',
            field=models.FloatField(default=10.0, help_text='Текущее количество энергии пользователя', verbose_name='Баланс монет ⚡️'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_daily_reward',
            field=models.DateTimeField(blank=True, help_text='Дата выдачи последнего ежедневного бонуса', null=True, verbose_name='Последняя награда'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Связь с базовой моделью авторизации', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
