# Generated by Django 6.0.3 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Пользователь')], default='user', help_text='Уровень доступа пользователя (RBAC)', max_length=20, verbose_name='Роль'),
        ),
    ]
