# Generated by Django 6.0.3 on 2026-06-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('roleplay', 'Сюжетная роль'), ('quiz', 'Тема квиза')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользовательский пресет',
                'verbose_name_plural': 'Пользовательские пресеты',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'mode', 'title')},
            },
        ),
    ]
